name: "Terraform Infrastructure CI/CD"
on:
 push:
   branches:
   - main

jobs:
 terraform:
   name: "Terraform Infrastructure"
   runs-on: ubuntu-latest
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
     - name: Set up Terraform
       uses: dflook/terraform-plan@v2
     - name: Terraform Init
       run: terraform fmt 
       